# Generated by Django 4.2.30 on 2026-05-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menuitem',
            table='MenuItems',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItems',
        ),
    ]
